DROP TABLE IF EXISTS EA_PRM;

CREATE TABLE EA_PRM (
	PRM_RECID SERIAL,
	PRM_TIMESTAMP TIMESTAMP,
	PRM_YEAR INT NOT NULL,
	PRM_MONTH INT NOT NULL,
	PRM_DAY INT NOT NULL,
	PRM_MAP VARCHAR(100) NOT NULL,
	PRM_PROC VARCHAR(100) NOT NULL,
	PRM_TYPE VARCHAR(100) NOT NULL,
	PRM_INDEG INT NOT NULL,
	PRM_OUTDEG INT NOT NULL,
	PRM_CENTR DECIMAL(6,4) NOT NULL,
	PRM_RANK DECIMAL(6,4) NOT NULL,
	PRM_PC DECIMAL(6,4) NOT NULL,
	PRM_OPT INT NOT NULL,
	INDEX(PRM_MAP),
	INDEX(PRM_PROC),
	INDEX(PRM_TYPE),
	INDEX(PRM_CENTR),
	INDEX(PRM_RANK),
	INDEX(PRM_PC),
	INDEX(PRM_OPT)
);